# Generated by Django 2.1.1 on 2018-09-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='abc', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='asd', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='fe', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='dfsa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.News'),
        ),
    ]
