# Generated by Django 2.1.1 on 2018-09-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20180912_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.News')),
            ],
        ),
    ]
